from . import regexhandlers
from . import hashtaghandlers
from . import idhandlers
from . import kontenthandlers
from . import statehandlers
from . import otherhanlers
from . import searchquran
from . import texthandlers
from . import help
from . import start
from . import echo
